### ISSUE TITLE
Better grouping of results

### ISSUE THREAD

**Issue by Wytamma** [smutch/mccoy#18]
The results folder is a bit of a mess. We should group the output based on the rule that generated them.

**Comment by smutch** [comment]
@Wytamma - quick question as I'm working through this...

In the online beast rule, the [shell command](https://github.com/smutch/mccoy/blob/f2490153b4fd8c9032e3f758141c3de9c1e702c9/mccoy/workflow/rules/onlinebeast.smk#L17) calls `online-beast` and produces an output file `{id}-beast.xml`, but then it looks like that file is never passed to `beast`. Instead it seems to get the xml file produced by `dynamic-beast`. Am I understanding that right and is this deliberate?

**Comment by Wytamma** [comment]
Yeah because we are using the templates `online-beast` doesn't actually change the XML files. Could pass the `online-beast` XML to `beast` but it shouldn't change anything.
